<?php

namespace FB\BetBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * BetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BetRepository extends EntityRepository
{
}
