<?php

namespace FB\BetBundle\Repository;

use Doctrine\ORM\EntityRepository;
use FB\FootballBundle\Entity\Game;
use FB\MemberBundle\Entity\User;

/**
 * BetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BetRepository extends EntityRepository
{
    public function findUserBet(User $user){
        $qb = $this->createQueryBuilder('b');
        $qb->where('b.user = :user')
            ->orderBy('b.id', 'DESC')
            ->setParameter('user', $user);

        return $qb->getQuery()->getResult();
    }

    public function findBetGame(Game $game){
        $qb = $this->createQueryBuilder('b');
        $qb->innerJoin('b.odd','o')
            ->where('o.game = :game')
            ->orderBy('b.id', 'DESC')
            ->setParameter('game', $game);

        return $qb->getQuery()->getResult();
    }

    
}
