<?php

namespace FB\BetBundle\Repository;

use Doctrine\ORM\EntityRepository;
use FB\MemberBundle\Entity\User;

/**
 * BetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BetRepository extends EntityRepository
{
    public function findUserBet(User $user){
        $qb = $this->createQueryBuilder('b');
        $qb->where('b.user = :user')
            ->orderBy('b.id', 'DESC')
            ->setParameter('user', $user);

        return $qb->getQuery()->getResult();
    }
}
