<?php

namespace FB\BetBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * LinkNameRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LinkNameRepository extends EntityRepository
{
    public function findNameTeam($name){
        $qb = $this->createQueryBuilder('l');
        $qb->where('l.teamNameApi = :name')
            ->setParameter('name', $name);

        return $qb->getQuery()->getSingleResult();
    }
}
