<?php

namespace FB\FootballBundle\Repository;

use Doctrine\ORM\EntityRepository;
use FB\FootballBundle\Entity\Game;

/**
 * GameRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GameRepository extends EntityRepository
{
    public function findNextGames(){
        $qb = $this->createQueryBuilder('g');
        $qb->where('g.dateMatch >= :date')
            ->setParameter('date', new \Datetime())
            ->setMaxResults(10)
            ->orderBy('g.dateMatch', 'ASC');

        return $qb->getQuery()->getResult();
    }

    public function findGameInProgress(){
        $qb = $this->createQueryBuilder('g');
        $qb->where('g.inprogress = true')
            ->orderBy('g.dateMatch', 'ASC');

        return $qb->getQuery()->getResult();
    }

    public function findGameEnded(){
        $qb = $this->createQueryBuilder('g');
        $qb->where('g.ended = true')
            ->orderBy('g.dateMatch', 'ASC');

        return $qb->getQuery()->getResult();
    }

    public function verificationGame(Game $game){
        $qb = $this->createQueryBuilder('g');
        $qb->where('g.dateMatch = :parisD')
            ->andWhere('g.homeTeam = :pariseq1')
            ->andWhere('g.awayTeam = :pariseq2')
            ->setParameter('parisD', $game->getDateMatch())
            ->setParameter('pariseq1', $game->getHomeTeam())
            ->setParameter('pariseq2', $game->getAwayTeam());

        return $qb->getQuery()->getResult();
    }
}
