<?php

namespace FB\FootballBundle\Repository;

use Doctrine\ORM\EntityRepository;
use FB\FootballBundle\Entity\Game;

/**
 * GameRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GameRepository extends EntityRepository
{
    public function findNextGames($ligue){
        $qb = $this->createQueryBuilder('g');
        $qb->where('g.dateMatch >= :date')
            ->andWhere('g.typeGame = :ligue')
            ->setParameter('ligue', $ligue)
            ->setParameter('date', new \Datetime())
            ->setMaxResults(10)
            ->orderBy('g.dateMatch', 'ASC');

        return $qb->getQuery()->getResult();
    }

    public function findAllNextGames(){
        $qb = $this->createQueryBuilder('g');
        $qb->where('g.dateMatch >= :date')
            ->setParameter('date', new \Datetime())
            ->setMaxResults(10)
            ->orderBy('g.dateMatch', 'ASC');

        return $qb->getQuery()->getResult();
    }

    public function findGameInProgress(){
        $qb = $this->createQueryBuilder('g');
        $qb->where('g.inprogress = true')
            ->orderBy('g.dateMatch', 'ASC');

        return $qb->getQuery()->getResult();
    }

    public function findGameEnded(){
        $qb = $this->createQueryBuilder('g');
        $qb->where('g.ended = true')
            ->orderBy('g.dateMatch', 'ASC');

        return $qb->getQuery()->getResult();
    }

    public function verificationGame($home, $away){
        $qb = $this->createQueryBuilder('g');
        $qb->Where('g.homeTeam = :pariseq1')
            ->andWhere('g.ended = false')
            ->andWhere('g.awayTeam = :pariseq2')
            ->setParameter('pariseq1', $home )
            ->setParameter('pariseq2', $away );

        return $qb->getQuery()->getOneOrNullResult();
    }
}
