<?php

namespace FB\FootballBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UpdateGameRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UpdateGameRepository extends EntityRepository
{
}
