<?php

namespace FB\StatsBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * DayStatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DayStatRepository extends EntityRepository
{
}
