site:
    resource: "@SiteBundle/Controller/"
    type:     annotation
    prefix:   /

accueil:
    resource: "@SiteBundle/Controller"
    type:     annotation
    prefix:   /

stats:
    resource: "@StatsBundle/Controller/"
    type:     annotation
    prefix:   /stats

football:
    resource: "@FootballBundle/Controller/"
    type:     annotation
    prefix:   /football

admin:
    resource: "@AdminBundle/Controller/"
    type:     annotation
    prefix:   /admin

support:
    resource: "@SupportBundle/Controller/"
    type:     annotation
    prefix:   /support

bet:
    resource: "@BetBundle/Controller/"
    type:     annotation
    prefix:   /bet

member:
    resource: "@MemberBundle/Controller/"
    type:     annotation
    prefix:   /member

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile