<?php

namespace FB\SupportBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TicketReplyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TicketReplyRepository extends EntityRepository
{
}
